version: '3.1'

services:

  mysql:
    image: mysql:${MYSQL_VERSION}
    volumes:
      - ../../volumes/mysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}
    ports:
      - 9876:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

  wp:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        WORDPRESS_VERSION: ${WORDPRESS_VERSION}
    volumes:
      - ./bin/wp-cli-custom:/usr/local/bin/wp-cli-custom:ro
      - ../../volumes/html/${WORDPRESS_VERSION}:/var/www/html:rw
      - ../src/theme:/var/www/html/wp-content/themes/my-theme:ro
      - ../src/plugin:/var/www/html/wp-content/plugins/my-plugin:ro
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=192.168.0.1
    depends_on:
      - mysql

  nginx:
    image: nginx:1.14.2-alpine
    ports:
      - 6789:6789
    volumes:
      - ./nginx-wp.conf:/etc/nginx/conf.d/default.conf:ro
      - ../../volumes/html/${WORDPRESS_VERSION}:/var/www/html:ro
    depends_on:
      - wp
